using System;
using System.Collections.Generic;

using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;


namespace ReformaTributaria.API.Model.Lista;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var classificacaoTributariaModel = ClassificacaoTributariaModel.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

public partial class RtcClassificacaoTributariaListaModel
{
    [JsonPropertyName("RST_COD_CST")]
    public string RstCodCst { get; set; }

    [JsonPropertyName("RST_DS_SITUACAO_TRIBUTARIA")]
    public string RstDsSituacaoTributaria { get; set; }

    [JsonPropertyName("RST_IND_GIBSCBS")]
    public ESimNao RstIndGibscbs { get; set; }

    [JsonPropertyName("RST_IND_GIBSCBSMONO")]
    public ESimNao RstIndGibscbsmono { get; set; }

    [JsonPropertyName("RST_IND_GRED")]
    public ESimNao RstIndGred { get; set; }

    [JsonPropertyName("RST_IND_GDIF")]
    public ESimNao RstIndGdif { get; set; }

    [JsonPropertyName("RST_IND_GTRANSFCRED")]
    public ESimNao RstIndGtransfcred { get; set; }

    [JsonPropertyName("RST_IND_GCREDPRESIBSZFM")]
    public ESimNao RstIndGcredpresibszfm { get; set; }

    [JsonPropertyName("RST_IND_REDUTORBC")]
    public ESimNao RstIndRedutorbc { get; set; }

    [JsonPropertyName("RCT_COD_CLASS_TRIB")]
    public string RctCodClassTrib { get; set; }

    [JsonPropertyName("RTA_COD_ANEXO")]
    public string RtaCodAnexo { get; set; }

    [JsonPropertyName("RCT_DS_CLASS_TRIB")]
    public string RctDsClassTrib { get; set; }

    [JsonPropertyName("RCT_NOME_CLASS_TRIB")]
    public string RctNomeClassTrib { get; set; }

    [JsonPropertyName("RCT_LC_REDACAO")]
    public string RctLcRedacao { get; set; }

    [JsonPropertyName("RCT_LC_214_25")]
    public string RctLc214_25 { get; set; }

    [JsonPropertyName("RCT_TIPO_ALIQUOTA")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long RctTipoAliquota { get; set; }

    [JsonPropertyName("RCT_PERC_RED_IBS")]
    public long RctPercRedIbs { get; set; }

    [JsonPropertyName("RCT_PERC_RED_CBS")]
    public long RctPercRedCbs { get; set; }

    [JsonPropertyName("RCT_IND_GTRIBREGULAR")]
    public ESimNao RctIndGtribregular { get; set; }

    [JsonPropertyName("RCT_IND_GCREDPRESOPER")]
    public ESimNao RctIndGcredpresoper { get; set; }

    [JsonPropertyName("RCT_IND_GMONOPADRAO")]
    public ESimNao RctIndGmonopadrao { get; set; }

    [JsonPropertyName("RCT_IND_GMONORETEN")]
    public ESimNao RctIndGmonoreten { get; set; }

    [JsonPropertyName("RCT_IND_GMONORET")]
    public ESimNao RctIndGmonoret { get; set; }

    [JsonPropertyName("RCT_IND_GMONODIF")]
    public ESimNao RctIndGmonodif { get; set; }

    [JsonPropertyName("RCT_IND_GESTORNOCRED")]
    public ESimNao RctIndGestornocred { get; set; }

    [JsonPropertyName("RCT_IND_NFEABI")]
    public ESimNao RctIndNfeabi { get; set; }

    [JsonPropertyName("RCT_IND_NFE")]
    public ESimNao RctIndNfe { get; set; }

    [JsonPropertyName("RCT_IND_NFCE")]
    public ESimNao RctIndNfce { get; set; }

    [JsonPropertyName("RCT_IND_CTE")]
    public ESimNao RctIndCte { get; set; }

    [JsonPropertyName("RCT_IND_CTEOS")]
    public ESimNao RctIndCteos { get; set; }

    [JsonPropertyName("RCT_IND_BPE")]
    public ESimNao RctIndBpe { get; set; }

    [JsonPropertyName("RCT_IND_BPETA")]
    public ESimNao RctIndBpeta { get; set; }

    [JsonPropertyName("RCT_IND_BPETM")]
    public ESimNao RctIndBpetm { get; set; }

    [JsonPropertyName("RCT_IND_NF3E")]
    public ESimNao RctIndNf3E { get; set; }

    [JsonPropertyName("RCT_IND_NFSE")]
    public ESimNao RctIndNfse { get; set; }

    [JsonPropertyName("RCT_IND_NFSEVIA")]
    public ESimNao RctIndNfsevia { get; set; }

    [JsonPropertyName("RCT_IND_NFCOM")]
    public ESimNao RctIndNfcom { get; set; }

    [JsonPropertyName("RCT_IND_NFAG")]
    public ESimNao RctIndNfag { get; set; }

    [JsonPropertyName("RCT_IND_NFGAS")]
    public ESimNao RctIndNfgas { get; set; }

    [JsonPropertyName("RCT_IND_DERE")]
    public ESimNao RctIndDere { get; set; }

    [JsonPropertyName("RCT_LINK_LEGISLACAO")]
    public string RctLinkLegislacao { get; set; }

    [JsonPropertyName("RCT_DT_INI_VIGENCIA")]
    public DateOnly RctDtIniVigencia { get; set; }

    [JsonPropertyName("RCT_DT_FIM_VIGENCIA")]
    public object RctDtFimVigencia { get; set; }

    [JsonPropertyName("RCT_DT_ATUALIZACAO")]
    public DateTimeOffset RctDtAtualizacao { get; set; }
}

public enum ESimNao { N, S };

public partial class RtcClassificacaoTributariaListaModel
{
    public static List<RtcClassificacaoTributariaListaModel> FromJson(string json) => JsonSerializer.Deserialize<List<RtcClassificacaoTributariaListaModel>>(json, Converter.Settings);
}

public static class Serialize
{
    public static string ToJson(this List<RtcClassificacaoTributariaListaModel> self) => JsonSerializer.Serialize(self, Converter.Settings);
}

internal static class Converter
{
    public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
    {
        Converters =
        {
            ESimNaoConverter.Singleton,
            new DateOnlyConverter(),
            new TimeOnlyConverter(),
            IsoDateTimeOffsetConverter.Singleton
        },
    };
}

internal class ESimNaoConverter : JsonConverter<ESimNao>
{
    public override bool CanConvert(Type t) => t == typeof(ESimNao);

    public override ESimNao Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        switch (value)
        {
            case "N":
                return ESimNao.N;
            case "S":
                return ESimNao.S;
        }
        throw new Exception("Cannot unmarshal type ESimNao");
    }

    public override void Write(Utf8JsonWriter writer, ESimNao value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case ESimNao.N:
                JsonSerializer.Serialize(writer, "N", options);
                return;
            case ESimNao.S:
                JsonSerializer.Serialize(writer, "S", options);
                return;
        }
        throw new Exception("Cannot marshal type ESimNao");
    }

    public static readonly ESimNaoConverter Singleton = new ESimNaoConverter();
}

internal class ParseStringConverter : JsonConverter<long>
{
    public override bool CanConvert(Type t) => t == typeof(long);

    public override long Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        long l;
        if (Int64.TryParse(value, out l))
        {
            return l;
        }
        throw new Exception("Cannot unmarshal type long");
    }

    public override void Write(Utf8JsonWriter writer, long value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value.ToString(), options);
        return;
    }

    public static readonly ParseStringConverter Singleton = new ParseStringConverter();
}

public class DateOnlyConverter : JsonConverter<DateOnly>
{
    private readonly string serializationFormat;
    public DateOnlyConverter() : this(null) { }

    public DateOnlyConverter(string? serializationFormat)
    {
        this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
    }

    public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return DateOnly.Parse(value!);
    }

    public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
}

public class TimeOnlyConverter : JsonConverter<TimeOnly>
{
    private readonly string serializationFormat;

    public TimeOnlyConverter() : this(null) { }

    public TimeOnlyConverter(string? serializationFormat)
    {
        this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
    }

    public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return TimeOnly.Parse(value!);
    }

    public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
}

internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
{
    public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

    private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

    private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
    private string? _dateTimeFormat;
    private CultureInfo? _culture;

    public DateTimeStyles DateTimeStyles
    {
        get => _dateTimeStyles;
        set => _dateTimeStyles = value;
    }

    public string? DateTimeFormat
    {
        get => _dateTimeFormat ?? string.Empty;
        set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
    }

    public CultureInfo Culture
    {
        get => _culture ?? CultureInfo.CurrentCulture;
        set => _culture = value;
    }

    public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
    {
        string text;


        if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
        {
            value = value.ToUniversalTime();
        }

        text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

        writer.WriteStringValue(text);
    }

    public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string? dateText = reader.GetString();

        if (string.IsNullOrEmpty(dateText) == false)
        {
            if (!string.IsNullOrEmpty(_dateTimeFormat))
            {
                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
            }
            else
            {
                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
            }
        }
        else
        {
            return default(DateTimeOffset);
        }
    }


    public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
}

#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603

