// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var classificacaoTributariaModel = ClassificacaoTributariaModel.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace ReformaTributaria.API.Model;

using System;
using System.Collections.Generic;

using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;

public partial class RtcClassificacaoTributariaModel
{
    [JsonPropertyName("CST")]
    public RtcCstModel Cst { get; set; }

    [JsonPropertyName("CodigoClassificacaoTributaria")]
    public string CodigoClassificacaoTributaria { get; set; }

    [JsonPropertyName("NomeClassTrib")]
    public string NomeClassTrib { get; set; }

    [JsonPropertyName("DescricaoClassificacaoTributaria")]
    public string DescricaoClassificacaoTributaria { get; set; }

    [JsonPropertyName("LC_Redacao")]
    public string LcRedacao { get; set; }

    [JsonPropertyName("LC_214_25")]
    public string Lc214_25 { get; set; }

    [JsonPropertyName("Tipo_Aliquota")]
    public ETipoAliquota TipoAliquota { get; set; }

    [JsonPropertyName("pRedIBS")]
    public long PRedIbs { get; set; }

    [JsonPropertyName("pRedCBS")]
    public long PRedCbs { get; set; }

    [JsonPropertyName("ind_gTribRegular")]
    public ESimNao IndGTribRegular { get; set; }

    [JsonPropertyName("ind_gCredPresOper")]
    public ESimNao IndGCredPresOper { get; set; }

    [JsonPropertyName("ind_gMonoPadrao")]
    public ESimNao IndGMonoPadrao { get; set; }

    [JsonPropertyName("ind_gMonoReten")]
    public ESimNao IndGMonoReten { get; set; }

    [JsonPropertyName("ind_gMonoRet")]
    public ESimNao IndGMonoRet { get; set; }

    [JsonPropertyName("ind_gMonoDif")]
    public ESimNao IndGMonoDif { get; set; }

    [JsonPropertyName("ind_gEstornoCred")]
    public ESimNao IndGEstornoCred { get; set; }

    [JsonPropertyName("dIniVig")]
    public string DIniVig { get; set; }

    [JsonPropertyName("dFimVig")]
    public string DFimVig { get; set; }

    [JsonPropertyName("DataAtualizacao")]
    public string DataAtualizacao { get; set; }

    [JsonPropertyName("ind_NFeABI")]
    public ESimNao IndNFeAbi { get; set; }

    [JsonPropertyName("ind_NFe")]
    public ESimNao IndNFe { get; set; }

    [JsonPropertyName("ind_NFCe")]
    public ESimNao IndNfCe { get; set; }

    [JsonPropertyName("ind_CTe")]
    public ESimNao IndCTe { get; set; }

    [JsonPropertyName("ind_CTeOS")]
    public ESimNao IndCTeOs { get; set; }

    [JsonPropertyName("ind_BPe")]
    public ESimNao IndBPe { get; set; }

    [JsonPropertyName("ind_BPeTA")]
    public ESimNao IndBPeTa { get; set; }

    [JsonPropertyName("ind_BPeTM")]
    public ESimNao IndBPeTm { get; set; }

    [JsonPropertyName("ind_NF3e")]
    public ESimNao IndNf3E { get; set; }

    [JsonPropertyName("ind_NFSe")]
    public ESimNao IndNfSe { get; set; }

    [JsonPropertyName("ind_NFSeVia")]
    public ESimNao IndNfSeVia { get; set; }

    [JsonPropertyName("ind_NFCom")]
    public ESimNao IndNfCom { get; set; }

    [JsonPropertyName("ind_NFAg")]
    public ESimNao IndNfAg { get; set; }

    [JsonPropertyName("ind_NFGas")]
    public ESimNao IndNfGas { get; set; }

    [JsonPropertyName("ind_DERE")]
    public ESimNao IndDere { get; set; }

    [JsonPropertyName("Anexo")]
    public string Anexo { get; set; }

    [JsonPropertyName("Link")]
    public Uri Link { get; set; }
}

public partial class RtcCstModel
{
    [JsonPropertyName("CodigoSituacaoTributaria")]
    public string CodigoSituacaoTributaria { get; set; }

    [JsonPropertyName("DescricaoSituacaoTributaria")]
    public string DescricaoSituacaoTributaria { get; set; }

    [JsonPropertyName("ind_gIBSCBS")]
    public ESimNao IndGIbsCbs { get; set; }

    [JsonPropertyName("ind_gIBSCBSMono")]
    public ESimNao IndGIbsCbsMono { get; set; }

    [JsonPropertyName("ind_gRed")]
    public ESimNao IndGRed { get; set; }

    [JsonPropertyName("ind_gDif")]
    public ESimNao IndGDif { get; set; }

    [JsonPropertyName("ind_gTransfCred")]
    public ESimNao IndGTransfCred { get; set; }

    [JsonPropertyName("ind_gCredPresIBSZFM")]
    public ESimNao IndGCredPresIbsZfm { get; set; }

    [JsonPropertyName("ind_gAjusteCompet")]
    public ESimNao IndGAjusteCompet { get; set; }

    [JsonPropertyName("ind_RedutorBC")]
    public ESimNao IndRedutorBc { get; set; }
}
[JsonConverter(typeof(JsonStringEnumConverter<ESimNao>))]

public enum ESimNao { Não, Sim };

public static class ESimNaoExtensions
{
    /// <summary>
    /// Retorna "S" para ESimNao.Sim e "N" para ESimNao.Não.
    /// Se o valor for null retorna "N".
    /// </summary>
    public static string ToSN(this ESimNao? value) =>
        (value ?? ESimNao.Não) switch
        {
            ESimNao.Sim => "S",
            ESimNao.Não => "N",
            _ => "N"
        };

    /// <summary>
    /// Versão para ESimNao não-nulo: retorna "S" para Sim e "N" para Não.
    /// </summary>
    public static string ToSN(this ESimNao value) =>
        value == ESimNao.Sim ? "S" : "N";
}

[JsonConverter(typeof(JsonStringEnumConverter<ETipoAliquota>))]

public enum ETipoAliquota { Fixa, Padrão, SemAlíquota, UniformeNacionalReferência, UniformeSetorial };

public partial class RtcClassificacaoTributariaListModel
{
    public static List<RtcClassificacaoTributariaModel> FromJson(string json) => JsonSerializer.Deserialize<List<RtcClassificacaoTributariaModel>>(json, Converter.Settings);
}

public static class Serialize
{
    public static string ToJson(this List<RtcClassificacaoTributariaModel> self) => JsonSerializer.Serialize(self, Converter.Settings);
}

internal static class Converter
{
    public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
    {
        Converters =
        {
            ESimNaoConverter.Singleton,
            ETipoAliquotaConverter.Singleton,
            new DateOnlyConverter(),
            new TimeOnlyConverter(),
            IsoDateTimeOffsetConverter.Singleton
        },
    };
}

internal class ESimNaoConverter : JsonConverter<ESimNao>
{
    public override bool CanConvert(Type t) => t == typeof(ESimNao);

    public override ESimNao Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        switch (value)
        {
            case "Não":
                return ESimNao.Não;
            case "Sim":
                return ESimNao.Sim;
        }
        throw new Exception("Cannot unmarshal type Ind");
    }

    public override void Write(Utf8JsonWriter writer, ESimNao value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case ESimNao.Não:
                JsonSerializer.Serialize(writer, "Não", options);
                return;
            case ESimNao.Sim:
                JsonSerializer.Serialize(writer, "Sim", options);
                return;
        }
        throw new Exception("Cannot marshal type Ind");
    }

    public static readonly ESimNaoConverter Singleton = new ESimNaoConverter();
}

internal class ETipoAliquotaConverter : JsonConverter<ETipoAliquota>
{
    public override bool CanConvert(Type t) => t == typeof(ETipoAliquota);

    public override ETipoAliquota Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        switch (value)
        {
            case "Fixa":
                return ETipoAliquota.Fixa;
            case "Padrão":
                return ETipoAliquota.Padrão;
            case "Sem alíquota":
                return ETipoAliquota.SemAlíquota;
            case "Uniforme nacional (referência)":
                return ETipoAliquota.UniformeNacionalReferência;
            case "Uniforme setorial":
                return ETipoAliquota.UniformeSetorial;
        }
        throw new Exception("Cannot unmarshal type TipoAliquota");
    }

    public override void Write(Utf8JsonWriter writer, ETipoAliquota value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case ETipoAliquota.Fixa:
                JsonSerializer.Serialize(writer, "Fixa", options);
                return;
            case ETipoAliquota.Padrão:
                JsonSerializer.Serialize(writer, "Padrão", options);
                return;
            case ETipoAliquota.SemAlíquota:
                JsonSerializer.Serialize(writer, "Sem alíquota", options);
                return;
            case ETipoAliquota.UniformeNacionalReferência:
                JsonSerializer.Serialize(writer, "Uniforme nacional (referência)", options);
                return;
            case ETipoAliquota.UniformeSetorial:
                JsonSerializer.Serialize(writer, "Uniforme setorial", options);
                return;
        }
        throw new Exception("Cannot marshal type TipoAliquota");
    }

    public static readonly ETipoAliquotaConverter Singleton = new ETipoAliquotaConverter();
}

public class DateOnlyConverter : JsonConverter<DateOnly>
{
    private readonly string serializationFormat;
    public DateOnlyConverter() : this(null) { }

    public DateOnlyConverter(string? serializationFormat)
    {
        this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
    }

    public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return DateOnly.Parse(value!);
    }

    public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
}

public class TimeOnlyConverter : JsonConverter<TimeOnly>
{
    private readonly string serializationFormat;

    public TimeOnlyConverter() : this(null) { }

    public TimeOnlyConverter(string? serializationFormat)
    {
        this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
    }

    public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return TimeOnly.Parse(value!);
    }

    public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
}

internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
{
    public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

    private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

    private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
    private string? _dateTimeFormat;
    private CultureInfo? _culture;

    public DateTimeStyles DateTimeStyles
    {
        get => _dateTimeStyles;
        set => _dateTimeStyles = value;
    }

    public string? DateTimeFormat
    {
        get => _dateTimeFormat ?? string.Empty;
        set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
    }

    public CultureInfo Culture
    {
        get => _culture ?? CultureInfo.CurrentCulture;
        set => _culture = value;
    }

    public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
    {
        string text;


        if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
        {
            value = value.ToUniversalTime();
        }

        text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

        writer.WriteStringValue(text);
    }

    public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string? dateText = reader.GetString();

        if (string.IsNullOrEmpty(dateText) == false)
        {
            if (!string.IsNullOrEmpty(_dateTimeFormat))
            {
                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
            }
            else
            {
                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
            }
        }
        else
        {
            return default(DateTimeOffset);
        }
    }


    public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
