using System.Text.Json;
using System.Text.Json.Serialization;

using ReformaTributaria.API.Utils.Enums;
using ReformaTributaria.API.Utils.Json.JsonConverter;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var classificacaoTributariaModel = ClassificacaoTributariaModel.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace ReformaTributaria.API.Model.Post;

public partial class RtcClassificacaoTributariaPostModel
{
    [JsonPropertyName("CST")]
    public RtcCstModel Cst { get; set; }

    [JsonPropertyName("CodigoClassificacaoTributaria")]
    public string CodigoClassificacaoTributaria { get; set; }

    [JsonPropertyName("NomeClassTrib")]
    public string NomeClassTrib { get; set; }

    [JsonPropertyName("DescricaoClassificacaoTributaria")]
    public string DescricaoClassificacaoTributaria { get; set; }

    [JsonPropertyName("LC_Redacao")]
    public string LcRedacao { get; set; }

    [JsonPropertyName("LC_214_25")]
    public string Lc214_25 { get; set; }

    [JsonPropertyName("Tipo_Aliquota")]
    [JsonConverter(typeof(ETipoAliquotaConverter))]
    public ETipoAliquota TipoAliquota { get; set; }

    [JsonPropertyName("pRedIBS")]
    public decimal PRedIbs { get; set; }

    [JsonPropertyName("pRedCBS")]
    public decimal PRedCbs { get; set; }

    [JsonPropertyName("ind_gTribRegular")]
    public ESimNao IndGTribRegular { get; set; }

    [JsonPropertyName("ind_gCredPresOper")]
    public ESimNao IndGCredPresOper { get; set; }

    [JsonPropertyName("ind_gMonoPadrao")]
    public ESimNao IndGMonoPadrao { get; set; }

    [JsonPropertyName("ind_gMonoReten")]
    public ESimNao IndGMonoReten { get; set; }

    [JsonPropertyName("ind_gMonoRet")]
    public ESimNao IndGMonoRet { get; set; }

    [JsonPropertyName("ind_gMonoDif")]
    public ESimNao IndGMonoDif { get; set; }

    [JsonPropertyName("ind_gEstornoCred")]
    public ESimNao IndGEstornoCred { get; set; }

    [JsonPropertyName("dIniVig")]
    public string DIniVig { get; set; }

    [JsonPropertyName("dFimVig")]
    public string DFimVig { get; set; }

    [JsonPropertyName("DataAtualizacao")]
    public string DataAtualizacao { get; set; }

    [JsonPropertyName("indNFeABI")]
    public ESimNao IndNFeAbi { get; set; }

    [JsonPropertyName("indNFe")]
    public ESimNao IndNFe { get; set; }

    [JsonPropertyName("indNFCe")]
    public ESimNao IndNfCe { get; set; }

    [JsonPropertyName("indCTe")]
    public ESimNao IndCTe { get; set; }

    [JsonPropertyName("indCTeOS")]
    public ESimNao IndCTeOs { get; set; }

    [JsonPropertyName("indBPe")]
    public ESimNao IndBPe { get; set; }

    [JsonPropertyName("indBPeTA")]
    public ESimNao IndBPeTa { get; set; }

    [JsonPropertyName("indBPeTM")]
    public ESimNao IndBPeTm { get; set; }

    [JsonPropertyName("indNF3e")]
    public ESimNao IndNf3E { get; set; }

    [JsonPropertyName("indNFSe")]
    public ESimNao IndNfSe { get; set; }

    [JsonPropertyName("indNFSeVia")]
    public ESimNao IndNfSeVia { get; set; }

    [JsonPropertyName("indNFCom")]
    public ESimNao IndNfCom { get; set; }

    [JsonPropertyName("indNFAg")]
    public ESimNao IndNfAg { get; set; }

    [JsonPropertyName("indNFGas")]
    public ESimNao IndNfGas { get; set; }

    [JsonPropertyName("indDERE")]
    public ESimNao IndDere { get; set; }

    [JsonPropertyName("Anexo")]
    public string Anexo { get; set; }

    [JsonPropertyName("Link")]
    public String Link { get; set; }
}

public partial class RtcCstModel
{
    [JsonPropertyName("CodigoSituacaoTributaria")]
    public string CodigoSituacaoTributaria { get; set; }

    [JsonPropertyName("DescricaoSituacaoTributaria")]
    public string DescricaoSituacaoTributaria { get; set; }

    [JsonPropertyName("ind_gIBSCBS")]
    public ESimNao IndGIbsCbs { get; set; }

    [JsonPropertyName("ind_gIBSCBSMono")]
    public ESimNao IndGIbsCbsMono { get; set; }

    [JsonPropertyName("ind_gRed")]
    public ESimNao IndGRed { get; set; }

    [JsonPropertyName("ind_gDif")]
    public ESimNao IndGDif { get; set; }

    [JsonPropertyName("ind_gTransfCred")]
    public ESimNao IndGTransfCred { get; set; }

    [JsonPropertyName("ind_gCredPresIBSZFM")]
    public ESimNao IndGCredPresIbsZfm { get; set; }

    [JsonPropertyName("ind_gAjusteCompet")]
    public ESimNao IndGAjusteCompet { get; set; }

    [JsonPropertyName("ind_RedutorBC")]
    public ESimNao IndRedutorBc { get; set; }
}


public partial class RtcClassificacaoTributariaPostModelX
{
    public static List<RtcClassificacaoTributariaPostModel> FromJson(string json) =>
        JsonSerializer.Deserialize<List<RtcClassificacaoTributariaPostModel>>(json, Converter.Settings);
}

public static class Serialize
{
    public static string ToJson(this List<RtcClassificacaoTributariaPostModel> self) => JsonSerializer.Serialize(self, Converter.Settings);
}

internal static class Converter
{
    public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
    {
        Converters =
        {
            ESimNaoConverter.Singleton,
            ETipoAliquotaConverter.Singleton,
            new DateOnlyConverter(),
            new TimeOnlyConverter(),
            IsoDateTimeOffsetConverter.Singleton
        },
    };
}









#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
